### ISSUE TITLE
Possible change to 'News' 

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#102]
Could 'News' be renamed 'Schedule'? both on the left hand menu and on the landing page?

**Comment by Chilipp** [comment]
We are working on setting up a schedule (see #75) but we are not there yet as there were other priorities. The _Schedule_ section will be added when we have a schedule of the first events. Or do we need it earlier than that?

The _News_ section is rather about containing stuff such as call for contributions (see #112), blog posts, etc., so I'd not remove it. Are you okay with that?

**Comment by ClaireWyatt** [comment]
Yes I'm okay with that. Good suggestions!
