### ISSUE TITLE
Add deadline dates

### ISSUE THREAD

**Issue by sdruskat** [SORSE/sorse.github.io#126]
- [ ] 1st deadline: rolling deadlines, last day of each month, 1st - 31 July
- [ ] 1st event: ???

**Comment by ClaireWyatt** [comment]
Please could the deadline dates for the rolling Call for Contributions be added to the 'Call for Contributions' page and the landing page?

**Call for Contribution rolling deadlines**
The Call for Contributions form will remain open continuously and there will be rolling deadlines. If you have a contribution, you can submit it whenever you want and you will be included in the next round of reviews. 

- First deadline date for contributions is 10th July 
- The Programme Team will get in touch with the contributors from this first round by the 17th July. 
- Second deadline date for contributions - 31st July
- More deadline dates to come! 
- Approximate end date for SORSE - March 2021

**Comment by eileen-kuehn** [comment]
Should we still update the text? 
Most information are included already except information about notification and approximate end of SORSE.

**Comment by ClaireWyatt** [comment]
Good point. I think we need to have some sentences to explain why, after saying that the deadline will be the end of the month, that the next deadline is the 10th July at midnight! It is currently confusing. 

So I suggest the following text to be inserted after the paragraph that ends 'sent for review by the Programme Committee' and before 'The call is open to anyone wanting..'

To kick start the series, the next few deadlines will be shorter to stimulate contributions. Following the end of July, contribution deadlines will be the end of the last day of each month. 
- First deadline date for contributions is 10th July at midnight UTC. 
- The Programme Team will get in touch with the contributors from this first round by the 17th July.
- Second deadline date for contributions is 31st July at midnight UTC.

**Comment by TeriForey** [comment]
@florianthiery can you update the text when you get back from lunch please? Thanks!
