### ISSUE TITLE
Create Zenodo Community

### ISSUE THREAD

**Issue by florianthiery** [SORSE/sorse.github.io#128]
we need some

**description** (A short description of the community collection, which will be displayed on the index page of the community)

sth for the **curration policy** (Please describe briefly and precisely the policy by which you accepted/reject new uploads in this community) 

any suggestions?

**Comment by TeriForey** [comment]
For the description we could probably use the same text as the website landing page?

**Comment by florianthiery** [comment]
I crated the community, be can modify the information in the future :-) https://zenodo.org/communities/sorse20/

**Comment by florianthiery** [comment]
Rename to sorse?

**Comment by florianthiery** [comment]
https://zenodo.org/communities/sorse/

**Comment by Chilipp** [comment]
Can you add our logo their @florianthiery ?

**Comment by Chilipp** [comment]
closing this as the community is set up
