### ISSUE TITLE
Add the organization committee members to the website

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#13]
Don't know how we should do this. Shall we create an Excel table and put it in the google drive and create a folder, where the people can upload their images?

We need to track somehow within this issue (or the excel file), how has already inserted his credentials and who hasn't

**Comment by TeriForey** [comment]
Need to double-check spreadsheet hasn't had any changes

**Comment by Chilipp** [comment]
I always named the latest version that I merged into the website with the commit hash. So you should see in the history of the Google spreadsheet, was changed since then
