### ISSUE TITLE
delete round corners in topic bazaar logo

### ISSUE THREAD

**Issue by florianthiery** [SORSE/sorse.github.io#133]
delete round corners in topic bazaar logo and set min-width a bit wider

example at 
https://rse-leaders.github.io/SORSE20/programme/bazaar/rse-in-the-digital-humanties-domain/

>@Chilipp hmm, das mit der Rundung ist nicht so schön, da muss ich den Style von minimal mistakes für diese eine Seite überschreiben

![image](https://user-images.githubusercontent.com/8138051/85300897-71ccb280-b4a7-11ea-9593-ee1c1a7caefb.png)

**Comment by Chilipp** [comment]
awaits decision on #134

**Comment by TeriForey** [comment]
This can go ahead now
