### ISSUE TITLE
Topic Bazaar Author content

### ISSUE THREAD

**Issue by TeriForey** [SORSE/sorse.github.io#134]
There's been a few changes to the Topic Bazaar items lately and I just wanted to take a moment to catch up on this.

I take it it's now all set up for having multiple authors and @florianthiery you've uploaded a logo for your topic? 

At the moment, the google form where we'll be taking new submissions from only provides an option for a single email address, one person's name and no way to upload a logo. I don't want the form to get too far out-of-sync, particularly as this might show some preference to existing topics. 

Can we pause any more changes to the topic bazaar until I've spoken to the rest of the team on how we want to proceed? We might want to update the form, or just allow everyone to update their own topic via GitHub but I think we need to have the conversation first.

**Comment by Chilipp** [comment]
sure. I also would not put all this into the topic bazaar form. but maybe highlight in the description that the authors can modify their topic via PR

**Comment by florianthiery** [comment]
yeah, let us pause it @TeriForey @Chilipp - the thing is I need more than one single person as contact, let us see what the team decides

**Comment by TeriForey** [comment]
@florianthiery do you need someone to contact all three addresses if they want to join? I'd would  be keen to hear your thoughts on why you need more than one contact email :)

**Comment by florianthiery** [comment]
hmm, ok, right, ... but maybe just one email, but optionally more than name

**Comment by florianthiery** [comment]
because there will be a team managing that not only me ;-) @TeriForey

**Comment by TeriForey** [comment]
Sure, I just want to make sure all the emails to a topic are picked up at the same rate. For some reason I'm wary about having more than one contact point - but I can't really describe why, so it might just be completely illogical! 

Either way, I've messaged the rest of the team and we'll try to get a solution/method of handling this sorted ASAP 👍

**Comment by florianthiery** [comment]
k, I am fine with only one email as contact, but we should allow "teams" to manage a bazaar topic @TeriForey does this make sense?

**Comment by florianthiery** [comment]
whats means there could be a team which is managing the topic in the backgroud and maybe this would be a nice idea to name the group and the people involved on the website, that was my idea @TeriForey :-)

**Comment by TeriForey** [comment]
Sure @florianthiery I completely agree with that

**Comment by florianthiery** [comment]
perfect :-) so back home ;-) enjoy the sun with the bicycle :-) @TeriForey

**Comment by florianthiery** [comment]
Any news from the TB group? @TeriForey

**Comment by TeriForey** [comment]
Hi @florianthiery 

Unfortunately no one has got back to me, but I've changed the google form to "Name(s)" so hopefully should make it easier for groups to submit a topic. I've left the single email-address but what I'm going to do is contact each person when they submit a topic pointing them towards this repo (and their topic file) and suggesting they make a PR if they want to change/update anything :) 

Should mean we're all good to go - can I just ask to be a reviewer in all PRs which are topic bazaar related from here on?

**Comment by florianthiery** [comment]
@TeriForey sounds like a good idea, you can maybe write a note that if it is a group, they should write the group name and (GROUP) in brackets and the contact persons seperated with a comma or sth else. One single email adress is perfect, so I will delte the multiple one from my topic. If you point them to the repo and they can do some PR this would be a nice idea :-)

If you want I can be the reviewer for TB PRs @Chilipp @TeriForey :-) than we can also add a logo if needed and so we have to fix issue https://github.com/RSE-leaders/SORSE20/issues/133 :-)

**Comment by sdruskat** [comment]
For what it's worth, I think duplicating bazaar content on the website is a maintenance nightmare. I'd actually jut post a link to the collab pad.

**Comment by TeriForey** [comment]
@sdruskat we're not using the collab pad for the SORSE topic bazaar. For the SORSE bazaar people submit using the google form, which we then add as topics to the website. It gives us the ability to add a few more details, like Florian's logo, and it means someone can't accidentally delete an item.

**Comment by Chilipp** [comment]
can this then be closed @TeriForey ?

**Comment by TeriForey** [comment]
Yes 👍
