### ISSUE TITLE
Issue with How do I get involved?

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#137]
_faq/howto/get-involved.md

On this page also, the left hand side menu doesn't have the programme pages. I think they should probably be there?

**Comment by Chilipp** [comment]
do you mean this part?
![image](https://user-images.githubusercontent.com/9960249/85308288-54044b00-b4b1-11ea-85be-975f9d4e519b.png)

As stated in #136, we should not change the sidebars on individual pages. But we could generally add the following section to every page:
![image](https://user-images.githubusercontent.com/9960249/85308443-82822600-b4b1-11ea-9cec-c17aa22ddb95.png)

**Comment by TeriForey** [comment]
By the way, if we add a 'get involved' to each page - we might want to include the topic bazaar under that heading since it's technically a different way to get involved

**Comment by ClaireWyatt** [comment]
agree with teri.

**Comment by TeriForey** [comment]
Don't want to add to all FAQ so moving on
