### ISSUE TITLE
Issue with FAQ

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#147]
_pages/faq.md

Do we need 'About' and 'How it works' underneath FAQ on any of the pages if FAQ goes to the same place?

This affects pages from 'Aims' down to and including 'Get involved'.

**Comment by sdruskat** [comment]
It's just a shortcut to the respective set of questions, and a second way to reach those subsets directly. Also, IMHO, it looks nicer to have links under the bold "section" headings (here: **FAQ**) in the menu. If there is a structural problem with this, I'm happy to change it, but I think it's fine the way it is.

**Comment by TeriForey** [comment]
Add 'submission' as a sub header to FAQ link.
