### ISSUE TITLE
'Ask us anything’ sessions page

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#148]
Please could you add a new page. 

**Ask us Anything sessions**

Each Wednesday at 10am BST you can sign up to a 'Ask us Anything' session held on zoom where you can put suggestions to us for an event, run through how your idea would work with the tools that we are planning to use or anything else! Sign up below for one of the sessions. 

1st July (link to google form on each date)
8th July 
15th July
22nd July
29th July

**Comment by sdruskat** [comment]
@ClaireWyatt Is there a draft for the form somewhere? Or an idea what should be on it? If not, something like this?

- Name
- Email address
- [ ] I consent to have the data in this form used for the SORSE folk to invite me to a Zoom meeting. The data in this form will be used to send the invitation per email, and will not be stored or used in any other way than to send the invitation.

**Comment by ClaireWyatt** [comment]
10am BST  - change to 11am UTC

**Comment by ClaireWyatt** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScGEP7WEdS9-iJ2COKlpobSKH-RJHNMO7bc-smw2KcyoSNO-w/viewform

**Comment by sdruskat** [comment]
Fixed in #170
