### ISSUE TITLE
new page - Sponsorship

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#150]
web team - this doesn't have to be in a bullet opint list if you think a table would look better? 

------
The SORSE committee is looking for sponsors to partner with us and get involved in delivering this series of events to the international RSE community. These sponsorship packages are valid for 6 months from the 1st July 2020 to December 2020. 

Get in touch with the Sponsorship Team, Claire and Max via sorse.enquiries@gmail.com 

The Exa and Peta packages can choose from one of these perks:
- VM/Cloud for workshops
- Award a Poster Prize (each poster session)
- Translation Services
- Subtitles services
- Host archiving of resources (TIB-AV)

**Exa - £5,000**

- 1 sponsored talks, workshops, software demo, panel at some point over the six months
- Sponsor of a guest speaker (chosen by the programme team)
- Virtual networking zoom breakout room, activated after the event, 1 a month
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session of the series

**Peta - £3,000**

- 1 sponsored talks, workshops, software demo, panel at some point over the six months
- Virtual networking zoom breakout room, activated after the event, 1 a month
- One chosen perk (list below)
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session of the series

**Terra - £1,000**

1 x sponsored poster
Virtual networking zoom breakout room, activated after the event, 1 a month
Blog post to the RSE Community on the SORSE website
Tweet mentioning sponsorship from SORSE twitter account
Access to registration data from ‘Opt-in’ attendees 
Logo included in sponsorship slide at beginning of each event
Logo, company description and link on the SORSE website 
Mention in the opening session

**Giga - £500**
Aimed at Open Source initiatives, charities and foundations

- 1 x sponsored poster
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session

**Comment by eileen-kuehn** [comment]
@ClaireWyatt, please note that *Tera* is written with one *r* only or is this intentional? Otherwise I will fix the typo :)

**Comment by ClaireWyatt** [comment]
thanks! that's my typo. good spot!
