### ISSUE TITLE
Match colour scheme with Logo

### ISSUE THREAD

**Issue by TeriForey** [SORSE/sorse.github.io#167]
Now that we have a logo, tweak some of the colours to match.

Also, bear in mind accessibility as in #47 

[ ] header
[ ] links
[ ] buttons

**Comment by trallard** [comment]
I would like to take on this! 

Just have a couple of questions ins anyone here privy about the fonts currently used? I would like to change them so that they are a bit more in line with the LOGO font too.

**Comment by Chilipp** [comment]
Hi @trallard! Thanks a lot, this would be great! 

> I would like to change them so that they are a bit more in line with the LOGO font too.

sure, no problem. Go ahead please, you have all the freedom that you want (we will review it later) :smiley: 

Would you actually like to be listed as a contributing member to the [website committee](https://sorse.github.io/contact/committees/#website)?

**Comment by trallard** [comment]
Sure why not!

**Comment by Chilipp** [comment]
great! What profile pic would you like to use? (can be an image file or url pointing to an image)

**Comment by trallard** [comment]
@Chilipp  will have to upload my photo to Cloudinary to provide the URL

**Comment by Chilipp** [comment]
We can alternatively also upload it to the repo, if you like
