### ISSUE TITLE
Issue with SORSE Committees

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#184]
_pages/contact/committees.md

'Organizing Committee' - please change this to 'Operating Committee'

**Comment by Chilipp** [comment]
@ClaireWyatt: should this only be changed in the name, or should we also change the identifier (which is currently `orga`, e.g. in https://sorse.github.io/contact/committees/#orga)

**Comment by ClaireWyatt** [comment]
@Chilipp in the identifier too (sorry!)
