### ISSUE TITLE
Issue with SORSE

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#189]
_pages/home.md

website logo not appearing on the twitter feed when linked to the website in a tweet. 

https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#tldr-too-long-didnt-read

**Comment by Chilipp** [comment]
actually this is already taken into effect by https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html. I'll have a look into what is going wrong here
