### ISSUE TITLE
page build fails

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#193]
no idea, why!

https://github.com/SORSE/sorse.github.io/runs/807347759

I cannot look into this at the moment as I am in a workshop

**Comment by Chilipp** [comment]
closed by #194

**Comment by TeriForey** [comment]
Think I've solved it. I added each part in to my fork one at a time, and it's the github setting in the config.yml file that breaks it.

```
github:
    username: *github
```

Without this extra setting it seems to build.

**Comment by TeriForey** [comment]
As you've got the image files @Chilipp would you be able to re-submit a PR with all the changes without the above? Or I could revert the revert and then make that small change?

**Comment by Chilipp** [comment]
great, thanks! sure, no problem

**Comment by TeriForey** [comment]
Fixed with PR #195
