### ISSUE TITLE
Export abstracts to PDF

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#215]
If we want to upload the abstracts to zenodo, we should make them available as PDF. My suggestion would be to use pandoc to convert the event page (markdown) to a PDF with a custom template. I could set up something to do this automatically and create the template. We should also make these PDFs available on the website for Download.

To automate this, I'd suggest to create a workflow that reacts on new pull requests, generate a PDF and opens a pull request into the _compare_ branch with the updated file. What do you think @vsoch? We'd need to install pandoc and latex, but this should be fairly simple using the [pandoc/latex](https://hub.docker.com/r/pandoc/latex) docker image.

But just to be sure: @eileen-kuehn, there are also possibilities to create PDFs out of Indico, right? Can we make one per (accepted) submission? And how would they look like?

**Comment by vsoch** [comment]
That definitely seems doable, and then upload as an artifact? Or actually add to the website so do a push or PR? I've done work with pdf generation via GitHub just once, and I think I used CircleCI (github didn't exist at time) and it seemed to work ok. https://github.com/openbases/openbases-pdf and https://github.com/openbases/builder-pdf. If the service you use Indico has an option that might be easier / more well-branded though.

**Comment by vsoch** [comment]
Is there a generic template you would want to use?

**Comment by Chilipp** [comment]
> Or actually add to the website so do a push or PR?

I thought about a PR into the PR that is about to change or add the abstract to the website.

> https://github.com/openbases/openbases-pdf and https://github.com/openbases/builder-pdf.

absolutely awesome! :heavy_check_mark: 

> Is there a generic template you would want to use?

No, I did not yet look around about already existing templates. I like the one from JOSS and it seems like you incorporated that already in [openbases-pdf](https://github.com/openbases/openbases-pdf) :+1:, but I am pretty agnostic. It should just include 

- our SORSE logo
- authors
- ORCids
- affiliations
- DOI
- a link to the event on our website

**Comment by vsoch** [comment]
This would be fun to work on! I think I'd like to update the current tooling to try and use a GitHub action. Can you show me an example markdown / bib (something else?) that you would want rendered?

**Comment by Chilipp** [comment]
what about the dummy ones from 4a2267c8cb532c0a0494f8180ee96758b39ebe38? They do not yet have an ORCid, but I'll add this in a bit

**Comment by vsoch** [comment]
hey @Chilipp ! Okay I have a GitHub action started (it's not ready for use here yet) https://github.com/rseng/pdf-generator and I want to discuss a few things before next steps. First, a few quick previews:

 - The example minimal template we can generate you can view here: https://github.com/rseng/pdf-generator/blob/master/paper/minimal.pdf Of course this is for a more robust markdown so it's likely to look better than the simple abstract counterpart.
 - Likely what we want to go for is the more "complex" template, here is a quick preview: https://github.com/rseng/pdf-generator/blob/master/paper/paper.pdf

And of course the sorse logo would be in the upper left instead. But here is where we should have discussion - what metadata goes in the left column? And what markdown fields should I look for, for each field? I likely am stopping work for today, but if you can tell me these fields and point to a file, I can put together a test for the action, and then come back here to talk about how we want it to trigger (e.g., would we want to add a variable to generate pdfs based on an input folder? And then into an output folder?) I'm also going to add a template to share the pdf on GitHub pages although I suspect we won't need that (we would just save as artifacts instead?)

**Comment by vsoch** [comment]
And here is a quick one with the sorse logo from the repo here - it has to be png afaik so we likely want one a little higher resolution. 

[paper.pdf](https://github.com/SORSE/sorse.github.io/files/4877238/paper.pdf)


Okay being bad, I should go to sleep :) Just wanted to try that out! Let's discuss the variables / markdown mapping and then I'll develop some strategy to generalize it for the action.

**Comment by eileen-kuehn** [comment]
> But just to be sure: @eileen-kuehn, there are also possibilities to create PDFs out of Indico, right? Can we make one per (accepted) submission? And how would they look like?

It is possible to get PDFs from contributions, e.g. for [test contribution](https://indico.scc.kit.edu/event/714/contributions/6514/) you only need to extend the url for `contribution.pdf` and voila you get a PDF: https://indico.scc.kit.edu/event/714/contributions/6514/contribution.pdf.
I have no idea if we can actually style this pdf in the way we want. Further it might happen, that information we don't want to be in there are printed. So I think generating the PDF ourselves might fit our workflow much better.

**Comment by Chilipp** [comment]
> it has to be png afaik so we likely want one a little higher resolution

@trallard: Could you provide a logo with a higher resolution that is suitable for print in the [above mentioned PDF](https://github.com/SORSE/sorse.github.io/files/4877238/paper.pdf)?

**Comment by Chilipp** [comment]
Concerning meta data:

from the markdown frontmatter, it's

```yaml
title: An awesome workshop
authors:
  - name: Workshop Guy
    affiliation: "From Somewhere on Earth"
  - name: Some One Else
    affiliation: "Another affiliation"
    orcid: 0000-0001-6171-7716
  - name: Some Guy
    affiliation: "Another affiliation"
date: 2020-07-11T18:00:00Z
doi: 10.5281/zenodo.90423948
category: workshop
```
`date` will be the date of publication (not the date and time of the event itself) that also appears on our website

Furthermore we should manually add the URL on the website (something like `pandoc -V website=sorse.github.io/programme/workshops/event-004/`)

**Comment by vsoch** [comment]
@Chilipp so for the metadata - could you list what you want in the left column,and then for other variables, where you want them? It would be helpful to be explicit because I have to update the template.

**Comment by Chilipp** [comment]
Hmm, from my feeling, the sidebar should contain:

```
DOI: $doi$
Links:
  - \href{https://sorse.github.io}{SORSE}
  - \href{$website$}{Event Website}
Category: $category$
Published: $date$
License:
<<your current text>
```

And the authors should be listed as you do, and maybe you can add an `ORCid` button next to it? You could use the `academicons` latex package for it (see https://tex.stackexchange.com/questions/275578/is-there-a-standard-way-to-include-orcid-in-tex-pdf)

hope this pseudo-code is understandable :sweat_smile:

**Comment by vsoch** [comment]
The orcid package is just a font file, we can look at that after the basics are addressed. Can you walk me through how the abstracts are to be discovered? In a folder? A list somewhere? I need to know how the action should expect to find them. How can I start to go about testing the action?

**Comment by vsoch** [comment]
@Chilipp what I can do is have an input file of full paths to different markdown files, and then loop through that. And so that would mean that the events should render into a text file we can use for that. Thoughts? If I can get a basic setup I can start actually creating the sorse template and action yaml.

**Comment by Chilipp** [comment]
>  Can you walk me through how the abstracts are to be discovered? In a folder?

yes, they are all located as `_events/*/event-???.md`, that's probably easier than a file

> How can I start to go about testing the action?

via PR into https://github.com/Chilipp/sorse.github.io maybe? Actually we could also take the master branch of my fork and make it a branch here. Would you prefer that?

**Comment by vsoch** [comment]
Let me first develop the ability to specify an input folder with markdowns, then I'll open a PR to your branch to test with the minimal template, then we'll update to an actual template (and add it to the repo) and go from there!

**Comment by vsoch** [comment]
```bash
$ find _events -regex '.*/[^/]*.md'
_events/workshops/event-004.md
_events/software_demos/event-002.md
_events/software_demos/event-001.md
_events/talks/event-003.md
```

**Comment by Chilipp** [comment]
looks good!

**Comment by Chilipp** [comment]
I'd suggest to put the PDF files with the same path, just ending in `.pdf` (i.e. when we convert `_events/workshops/event-004.md`, the PDF file should be rendered at `_events/workshops/event-004.pdf`)
