### ISSUE TITLE
Add Calendar feed

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#216]
In #209 we are adding a calendar to display the events on our webpage. Using the [ics](https://github.com/adamgibbons/ics) Javascript library, it should also be pretty straight-forward to make them available for download as `.ics` file. Both solutions are static as such that the website user always has to check our website whether the information are still correct. 

I suggest therefore to generate a workflow that takes events from our webpage on every push to the master branch, and puts/updates them on a public Google Calendar using the [Calendar API](https://developers.google.com/calendar/quickstart/python).

Does this sound reasonable? I never did something like this before, so I am looking forward for feedback!

**Comment by vsoch** [comment]
@Chilipp I guess I feel a little bit uneasy about needing to put a Google credential in a workflow. If we need the events to be in Google for sharing (and I just searched and it seems very tough to do this with fullcalendar) why not start with them there, and then have the feed available to subscribe to? Or maybe there is some "third party" workaround where we could have an "express interest in this event" button, and then have a calendar invite sent from that?  Or maybe something like https://github.com/carlsednaoui/add-to-calendar-buttons?

**Comment by Chilipp** [comment]
Hey @vsoch! Yes, the add-to-calendar-button is indeed much better than the `.ics` thing I proposed, so we should go for that.

I would not have problems putting the Google credentials in a workflow, I'd just make a new account for it (or we use the SORSE.enquiries@gmail.com account) rather than using my personal account. The reason why I think something like this might be useful is that the `.ics`, as well as the `add-to-calendar` thing does not inform the website user when we have to change date or time of the event. That's why I thought it makes sense to put it in a public google calendar that everyone can use. Having it as a form of CD would just mean that we only have to maintain one thing (the website), rather than two things (website and google calendar). Or do you think it's too much of an overkill for such a simple task?

**Comment by vsoch** [comment]
Personally I try to be conservative with implementing complicated integrations, and especially when credentials or involved, so if this were my repository I would say it's overkill and risky for a simple task. But I understand that people have different appetite for risks, and my preference might not be the best choice for the repository here.

**Comment by Chilipp** [comment]
> so if this were my repository

it is your repository as it is mine :wink: 

> I would say it's overkill and risky for a simple task

agreed, so let's do it manually. I have to admin that I tend to exaggerate with automation... :sweat_smile:

**Comment by vsoch** [comment]
> agreed, so let's do it manually. I have to admin that I tend to exaggerate with automation... sweat_smile

I think this is okay :) Automation is great!
