### ISSUE TITLE
Create a legend for the calendar

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#225]
follow-up of #224, see https://github.com/SORSE/sorse.github.io/pull/224#issuecomment-658391996

**Comment by vsoch** [comment]
@Chilipp do we really need this now that it's readable?

**Comment by Chilipp** [comment]
I'm fine without it. But I thought you would like to have it :sweat_smile: Feel free to close this if you are happy with the current solution, too

**Comment by vsoch** [comment]
okay! I think if some future addition warrants more different colorings, it would be useful to have. Let's leave it open for future people to see / comment on / work on (including myself!)
