### ISSUE TITLE
Issue with SORSE - Call for Contributions

### ISSUE THREAD

**Issue by ClaireWyatt** [SORSE/sorse.github.io#233]
_posts/programme/2020-06-23-call-for-contributions.md

Please could you replace this text "We encourage contributions from all time zones and will schedule events on a day and at a time that suits the presenter. Events will be recorded so that they can be run multiple times to suit different time zones and encourage those communities to come together to network."

with this text:
"We encourage contributions from all time zones and will schedule events on a day and at a time that suits the presenter.   We would like to record events where appropriate. The Call for Contribution form **_asks for your permission to record the event_**, for **_you to give permission to provide your materials under a CCBY licence_** and **_be happy to add them to Zenodo_**. 

We ask for these permissions so that 1) commmunity members in different timezones can watch your event and 2) we can build an RSE resource on many different topics. "

**Comment by Chilipp** [comment]
Hi @ClaireWyatt! I can do this later this evening.

But is it really _all your materials_ or only the material submitted via indico?

**Comment by ClaireWyatt** [comment]
EVERYTHING THEY OWN OR HAVE EVER MADE! No, okay, just the materials submitted to indico or used at hte event like slides, poster, that kind of thing. (feel free to make changes)

**Comment by Chilipp** [comment]
Alright, I'll change the text. As far as I remember we did not want to force presenters to upload the slides, etc., but rather recommended to do so. But I'll look it up again later

**Comment by ClaireWyatt** [comment]
Danke schon!
