### ISSUE TITLE
Issues with rendering Events in Safari

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#235]
There seem to be several issues regarding the rendering in Safari (issue seems to exist in different versions of Safari):

1. When looking at the events the legend for presenting author should show a star (*) but currently is displayed as 1
<img width="279" alt="Screenshot 2020-07-17 at 18 02 40" src="https://user-images.githubusercontent.com/8090701/87806825-bb66ae00-c857-11ea-9d1e-14c39e81df5b.png">

2. The button for adding the event to the calendar is not rendered at all
<img width="933" alt="Screenshot 2020-07-17 at 18 05 47" src="https://user-images.githubusercontent.com/8090701/87807750-f5847f80-c858-11ea-89c3-5a7d33a801e3.png">

**Comment by Chilipp** [comment]
really? not for me, see http://www.philipp-s-sommer.de/sorse.github.io/programme/software-demos/event-002/

![image](https://user-images.githubusercontent.com/9960249/87807104-231cf900-c858-11ea-9f08-49f0962e1bb1.png)

**Comment by Chilipp** [comment]
closed by #241
