### ISSUE TITLE
Timezones rendered in Calendar view and Event view seem to differ

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#237]
The views seem to be based on different timezones. The calendar view seems to adapt to my local timezone whereas the event view displays times in UTC. This feels somewhat confusing.

**Comment by Chilipp** [comment]
with _event view_ you mean the webpage, such as http://www.philipp-s-sommer.de/sorse.github.io/programme/software-demos/event-001/, right? Yes, this should be fixed, but I don't know yet how. At least we have to add a _UTC_ every time

**Comment by eileen-kuehn** [comment]
Yes, correct!

**Comment by Chilipp** [comment]
added _UTC_ with b339573 but we need a better solution here
