### ISSUE TITLE
"Schedule of events" links to main page

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#238]
The call-for-contributions site links to the "Schedule of events". This link currently goes to the main page and thus visitors don't immediately see a real schedule but instead have to scroll a lot until they find the events calendar.

We could directly link to the calendar on the main page for example (#upcoming-events) or directly to the Programme.

**Comment by Chilipp** [comment]
thanks! I'll implement this when working on #233
