### ISSUE TITLE
Events are opening in new window

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#240]
The ``target`` for event listings, e.g. at http://www.philipp-s-sommer.de/sorse.github.io/programme/#workshop is ``_blank``. All other links directly render in the same window, so this should be removed.

**Comment by vsoch** [comment]
I think the rationale here is that the user might want to browse through the list, and open a bunch of events without losing the current window. It might be totally subjective, but I think _blank is used appropriately in this case!

**Comment by eileen-kuehn** [comment]
Usually if I want to check several pages I explicitly use shortcuts for opening new tabs. I don't want to have the website decide for me especially as this are all internal links. But this is really just opinion-based. For me it feels wrong :)

**Comment by Chilipp** [comment]
yes, I have a better methodology in my mind. I also don't like the current behavior. I'll make a separate PR for this, but this should not block merging of #223
