### ISSUE TITLE
Styling of events in calendar / list views

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#244]
*This is again opinion-based, so please close, if this feels wrong ;)*

When looking at the different [calendar views](http://www.philipp-s-sommer.de/sorse.github.io/programme/calendar/) and the list view of the calendar it feels like the *Submission deadlines* and *Ask us anything* sessions are more important than the actual contributions. The contributions are neither bold nor have underlying color and therefore seem to be less important.

**Comment by Chilipp** [comment]
I had it as blocks, but this also looked weird as the time has been truncated (see https://619-267395254-gh.circle-artifacts.com/0/SORSE/programme/calendar/index.html for instance, or screenshot below). But yes, definitely something that we should care about

![image](https://user-images.githubusercontent.com/9960249/87816264-5adf6d00-c867-11ea-9625-6b3619f05e1b.png)
