### ISSUE TITLE
PDF does not render all authors

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#265]
The PDF for contribution with ID ``012`` does not contain all authors in the top, only in the footer (see [rendered PDF](https://github.com/SORSE/sorse.github.io/blob/master/downloads/event-012.pdf)). The [contribution](https://github.com/SORSE/sorse.github.io/blob/master/_events/talks/event-012.md) itself is a bit special as it does not contain any affiliations.

**Comment by Chilipp** [comment]
closed via #268
