### ISSUE TITLE
Out of date abstract submission date

### ISSUE THREAD

**Issue by andrewgait** [SORSE/sorse.github.io#297]
In case you missed it on Slack, it has just been pointed out:

Also just a heads up the current form has 'For the current submission deadline we are accepting sessions that will be delivered after 24th July.' which may no longer be relevant.

I guess this is an Indico issue but I thought I would flag it here in case people aren't checking Slack.

**Comment by Chilipp** [comment]
Thanks @andrewgait ! @cc-a , could you quickly check in indico?

**Comment by eileen-kuehn** [comment]
I just removed it from the description of abstract fields. I suppose the issue can be closed now?

**Comment by Chilipp** [comment]
Thanks!
