### ISSUE TITLE
Cleanup of launch event

### ISSUE THREAD

**Issue by eileen-kuehn** [SORSE/sorse.github.io#311]
As mentioned by @ClaireWyatt in [Slack](https://ukrse.slack.com/archives/GTATB7ATS/p1599122127033300) we need to cleanup some things regarding the kick-off event including:

* [x] removing button in the top banner on front page
* [x] changing text on kick off page to past tense
* [x] removing join and register buttons
* [x] ~~adding materials, if available to indico~~
* [x] integrating the recoding

**Comment by sdruskat** [comment]
Hi @eileen-kuehn, sorry for commandeering this, I had some time to spare.

**Comment by eileen-kuehn** [comment]
> Hi @eileen-kuehn, sorry for commandeering this, I had some time to spare.

That's great, I really appreciate your work! I only had to undo some of my changes ;)
