### ISSUE TITLE
Google calendar issues on mobile devices

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#315]
Via slack:

> I’m trying to add the SORSE event calendar to my google cal, but that fails when I click the link. When adding it through the menu, it tells me the URL is invalid. It’s the link on the SORSE programme page: 
> https://calendar.google.com/calendar?cid=YXRnbTJiNXZiam42dGpyaTllNHI1a2tra2NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
Any idea whar could be going wrong here?  

> Ah just for completeness: this is just a problem with the mobile browser version of google cal. Asking for the desktop sote solved it...

**Comment by sdruskat** [comment]
Vote to close, as this is an issue with Google's calendar platform mobile site, nothing to do on our side.

**Comment by ygrange** [comment]
Well, I would vote for adding a sentence about this in or near the link.

**Comment by Chilipp** [comment]
Sorry @ygrange totally forgot about this issue. But I am closing it as the series is about to end
