### ISSUE TITLE
HTML test failure of PIK website

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#327]
there seems to be a problem with the site of personal website of @tscheypidi (https://www.pik-potsdam.de/research/members/dietrich) which is why the link checking in the CI is failing. But I suspect, PIK will resolve this soon, so I'll check from time to time.

Otherwise, if anything changed @tscheypidi, please tell me the correct url

**Comment by tscheypidi** [comment]
@Chilipp Thanks for the notification. Our institute just updated the website design and apparently also changed some URLs in that context. I created a PR with the updated address: #328
