### ISSUE TITLE
Wording for adding events to users calendar

### ISSUE THREAD

**Issue by catsmith** [SORSE/sorse.github.io#343]
I agreed to make a PR for this in the meeting yesterday but I can't find the code for the calendar.

The links for a user to add all SORSE events to their calendar is a little confusing (I misunderstood it as 'register for all events') so we agreed in the meeting it should be changed to 'Add all events to your calendar' rather than 'subscribe to all events' as is currently the case.

**Comment by Chilipp** [comment]
It's https://www.github.com/SORSE/sorse.github.io/tree/master/_includes%2Fupcoming-events.html and https://github.com/SORSE/sorse.github.io/blob/master/_layouts/calendar.html
