### ISSUE TITLE
publish events to Zenodo

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#350]
the first ones have been published and submitted to Zenodo (manually), but nothing happened since then (and I could not find the time so far). Ideally we have an automated way using the [Zenodo RestAPI](https://developers.zenodo.org/#rest-api), but otherwise the workflow is described in https://docs.google.com/document/d/1EExW-DRT1bA4CxZYOC5xCbr5NpNJGTRLn4hPAr8v2Sg/edit

**Comment by johanphilips** [comment]
We should get an access token, preferbly linked to SORSE github organisation instead of my own profile :) Via [here](https://zenodo.org/account/settings/applications/tokens/new/). @Chilipp assuming you have admin rights for the SORSE organisation, could you get the access token?

**Comment by Chilipp** [comment]
you need a personal access token @johanphilips. So you need to register on zenodo and generate your own token. 

The workflow is such that you do make your submission, publish it and claim it to be part of the SORSE community. After it has been published, @florianthiery (who is the admin of the SORSE community on zenodo) has to approve that this is indeed part of SORSE.

**Comment by Chilipp** [comment]
But please correct me if I am wrong @florianthiery .

**Comment by johanphilips** [comment]
personal access token would also work, it would be an environment variable or argument in the script anyway. Is it fine to develop a standalone script first and afterwards see if we could integrate it with [sorse-data-filter](https://github.com/SORSE/sorse-data-filter)? The integration could directly use the extracted metadata from indico instead of parsing the md output.

**Comment by florianthiery** [comment]
> But please correct me if I am wrong @florianthiery .

I think you are right

**Comment by Chilipp** [comment]
Fine with me. Although we should keep in mind that 

1. The doi has to be added to the markdown file (see https://www.github.com/SORSE/sorse.github.io/tree/master/_events%2Ftalks%2Fevent-005.md for instance)
2. The PDF has to be rebuild to include the doi (see https://github.com/SORSE/sorse.github.io/blob/master/downloads/event-005.pdf)
3. The regenerate PDF has to be added to the zenodo archive and the repo on GitHub

So the general workflow should be like

1. First request to create the archive and reserve the doi
2. Add the doi to the md file
3. Rebuild the PDF
4. Add the PDF to the archive (2nd request)
5. Add the PDF to the repo on GitHub
6. Make a PR
7. Merge into master
8. Publish the archive (3rd request)

**Comment by Chilipp** [comment]
You could probably also directly work with the md files from this repo, independent of Indico. For the pdf- generation we use openbases-paper to extract the stuff, and they do provide a python API (https://openbases.github.io/openbases-python/html/usage.html#python-client). @vsoch should know more about this

**Comment by johanphilips** [comment]
Ok, thanks. And are the md files flagged if they are already published?

**Comment by Chilipp** [comment]
The ones that are published already do have an associate doi in the Frontmatter (such as event-005.md).

**Comment by Chilipp** [comment]
Note that the one from https://github.com/SORSE/sorse.github.io/pull/339 should be excluded as it's a partner event

**Comment by johanphilips** [comment]
I gave the Zenodo API a try and it is straightforward to deposit and publish via python requests. If you want to integrate it with the PR and merge workflow, the last publish request should ideally be triggered from within the CI pipeline, e.g. with `cURL`: 

```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{'access_token': $ACCESS_TOKEN}' \
  https://zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish
```

**Comment by johanphilips** [comment]
I could spend some time today on the upload script. It's currently on a private GitHub [repo](https://github.com/johanphilips/sorse-zenodo-upload). Should I invite you there or just put a branch here?

**Comment by Chilipp** [comment]
Hi @johanphilips ! Great news, thanks a lot :smiley: both is fine for me, so do as you like

**Comment by johanphilips** [comment]
Currently events are deposited in Sandbox (not published).
![image](https://user-images.githubusercontent.com/67114042/100463785-af73de00-30cc-11eb-808b-afb3650451a6.png)

**Comment by johanphilips** [comment]
Published one foobar event: https://sandbox.zenodo.org/record/703104#.X8EZv3lKiUk

**Comment by johanphilips** [comment]
See [this repo](johanphilips/sorse-zenodo-upload) for automated Zenodo upload (incl. regeneration of md files and pdf files).

**Comment by Chilipp** [comment]
Absolutely awesome! Thanks a lot @johanphilips! So the next steps would be to run it and publish them, right? Do you want me to run it and make the PR

**Comment by johanphilips** [comment]
What’s the policy? I publish them to Zenodo in sorse community or does it involve a review step? I could make a PR and put the script in your scripts folder but have no experience with GH workflow actions that could be used to replace the Docker call in the script. I’m used to GitLab CI 😁

**Comment by johanphilips** [comment]
I am moving it to scripts folder and testing it on the _events folder but there seem to be some issues with particular files. Is the front matter all in the same format?

**Comment by johanphilips** [comment]
Some events do not have affiliations set and some do not have author affiliation:
```
...
INFO:root:Found event Towards Knowledge Graphs of Research Software metadata (..\_events\talks\event-010.md)
INFO:root:Event already deposited! Check DOI 10.5281/zenodo.3977916. Skipping...
ERROR:root:Could not find a title or affiliations in the frontmatter in event ..\_events\talks\event-012.md, check file contents.
INFO:root:Found event Becoming a self-employed RSE web developer. (..\_events\talks\event-014.md)
INFO:root:Creating new deposition for ..\_events\talks\event-014.md
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sandbox.zenodo.org:443
...
```

**Comment by johanphilips** [comment]
For review: https://sandbox.zenodo.org/search?page=1&size=20&q=ecfunded&sort=mostrecent
Log: 
[sorse_zenodo_upload.log](https://github.com/SORSE/sorse.github.io/files/5610339/sorse_zenodo_upload.log)

**Comment by johanphilips** [comment]
New script in https://github.com/SORSE/sorse.github.io/tree/zenodo-upload-sandbox/scripts and example files in https://github.com/SORSE/sorse.github.io/tree/zenodo-upload-sandbox/ci

**Comment by Chilipp** [comment]
Hey @johanphilips ! Thanks again for all of this and my apologies that I am a bit unresponsive. But I'll have a detailed look at it and try it myself before Monday.

Concerning the affiliations: yes there are a couple of them but unfortunately there is nothing we can do about. Does zenodo require an affiliation?

**Comment by Chilipp** [comment]
I thought about it once more and I think we are fine with keeping it simple for the moment and not adding a GitHub workflow for this (unless you want to). I am also fine with keeping this in a separate repo and just add a note to the README of this repository here, but that's up to you.

**Comment by johanphilips** [comment]
No worries, I’ve already moved the script to the scripts folder of this repo, do keep in mind that it still calls docker via subprocess. The tests on the sandbox were successful, see [this branch](https://github.com/SORSE/sorse.github.io/tree/zenodo-upload-sandbox/)

**Comment by Chilipp** [comment]
hi @johanphilips! Can we open a draft PR to continue the work on this?

**Comment by johanphilips** [comment]
Sure, I am not that familiar with your workflow, do we start from the [sandbox branch](https://github.com/SORSE/sorse.github.io/tree/zenodo-upload-sandbox/)?

**Comment by Chilipp** [comment]
Yep
