### ISSUE TITLE
add Download Slides button

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#352]
when slides have been submitted

**Comment by cc-a** [comment]
Hi @Chilipp, I'm happy to have a crack at this.

**Comment by Chilipp** [comment]
thanks a lot @cc-a! I'd just add the possibility to add a url to the yaml front matter and add a button to the [bottom where the other buttons are](https://github.com/SORSE/sorse.github.io/blob/master/_layouts/event.html). Let me know, if you have any problems :smiley:

**Comment by Chilipp** [comment]
closed via #355
