### ISSUE TITLE
Broken link in event-016

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#365]
@annalenalamprecht, seems like there is a broken link in [your workshop abstract](https://sorse.github.io/programme/workshops/event-016/) to the ReSA Taskforce, namely http://www.researchsoft.org/resa-taskforces-join-us/. Could you please provide the correct one?

**Comment by andrewgait** [comment]
@Chilipp it looks like the correct link should be https://www.researchsoft.org/taskforces/, I think?

**Comment by annalenalamprecht** [comment]
@Chilipp @andrewgait Yes, that seems like the right link. 
@mkuzak has submitted this abstract and will know for sure.
