### ISSUE TITLE
nordic-rse logo is missing

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#397]
hey @bast! seems like the nordic-rse logo is not available anymore at https://nordic-rse.org/img/logo.png which is why the CI for this repository is failing

Could you please provide a new URL that we can add to

https://github.com/SORSE/sorse.github.io/blob/879fb83116cb82271d2aa2324709d0ceaf6c305a/_data/committee/national_chapters.yml#L38-L46

?

**Comment by bast** [comment]
Sorry that I broke that. I will fix that with a pull request in a moment.
