### ISSUE TITLE
broken link to research-software.nl

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#416]
hey @vsoch! happy new year :smiley: 

seems like you're event has a broken link to https://www.research-software.nl (see https://sorse.github.io/programme/discussions/event-013/ and https://app.circleci.com/pipelines/github/SORSE/sorse.github.io/1024/workflows/842bd5f3-58fb-4655-a0ca-9abbaef932b4/jobs/1719 for instance). Any idea, why?

**Comment by vsoch** [comment]
hey @Chilipp ! The site is maintained by the RSE group in the Netherlands, and the speaker from our event that you'd want to ask is @jspaaks.

**Comment by vsoch** [comment]
oops I just tried to assign @jspaaks and I messed it up :/

**Comment by Chilipp** [comment]
the website is up again so we can close this issue

**Comment by jspaaks** [comment]
Hi All and happy new year. 

There were some memory problems with research-software.nl over the holidays. For the time being we put a band-aid on it, hopefully we'll have time to do a more structural fix in the next couple of days.

**Comment by vsoch** [comment]
Thanks for the update @jspaaks! Happy New Year to you too :)
