### ISSUE TITLE
RSS feed doesn't display events

### ISSUE THREAD

**Issue by unode** [SORSE/sorse.github.io#453]
Hi everyone,

We are using the RSS feed (https://sorse.github.io/feed.xml) to fetch the latest events from SORSE however it seems the feed hasn't changed since January despite new events being listed.
For instance today's "How FAIR is your software?" event isn't included.
Any chance of having this fixed?

Thanks

**Comment by Chilipp** [comment]
dear @unode! Yes, my apologies. The RSS feed is not supported for the website, sorry. Did you find a link to it anywhere on the website?

**Comment by unode** [comment]
Hi @Chilipp I can't seem to find it by searching the page but it is there if looking at the source code.

**Comment by unode** [comment]
Was about to edit my initial question but you were quicker! Thanks for the quick reply!
Is [Google Calendar](https://calendar.google.com/calendar?cid=YXRnbTJiNXZiam42dGpyaTllNHI1a2tra2NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) the recommended way to be up to date with latest events?

**Comment by Chilipp** [comment]
sure, it's generated by default for posts. But the `_events` are a collection which is why they do not appear. not sure, how to fix this for the moment. but we are anyway running the last couple of events during the next weeks, so it won't be fixed probably.

> Is Google Calendar the recommended way to be up to date with latest events?

yes, unfortunately this is the only possibility

**Comment by unode** [comment]
> last couple of events during the next weeks

Ah! I missed this :(
I guess we can close this until future endeavours.

Thanks for the feedback!
