### ISSUE TITLE
Add content for Awards team

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#49]
The [awards page](../blob/master/_pages/programme/awards.md) is still empty and needs content

This issue is a followup of #24 and #7

**Comment by Chilipp** [comment]
@annalenalamprecht and @sandragesing. Shall we hide this page on the website until we have something to show? It is probably not relevant for the call for contributions anyway, isn't it?

**Comment by annalenalamprecht** [comment]
@Chilipp Yes, I think you can hide it for the moment, it is indeed not really relevant for the CfC.
