### ISSUE TITLE
Edit social accounts in _config.yml

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#58]
There are a few unknown in _config.yml that need some information. For twitter and Instagram, the question is what we will use (if anything at all)

- [ ] Twitter
- [ ] Website (sorse20.researchsoftware.org or researchsoftware.org/SORSE20), already in the discussion with @alysbrett
- [ ] Instagram
- [ ] Github: Will be https://github.com/RSE-leaders/SORSE20

**Comment by TeriForey** [comment]
No instagram 

Twitter account is coming

**Comment by TeriForey** [comment]
I'm going to suggest we remove all of these from the footer.

There's already links to the GitHub page with the edit buttons, we'll be showing the Twitter stream on the frontpage (with handle visible) and we don't have really anything else that needs to be in that part. Also, there's also a lot going on in the footer.
