### ISSUE TITLE
Create event framework

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#75]
As a followup on #15, we need to setup a structure for the content of events (see the _second PR_ in https://github.com/RSE-leaders/SORSE20/issues/15#issuecomment-642940625). 

We need to add events to the front page, which should show closest the upcoming events, and we need to add a page that shows all events.

@vsoch suggested to use a combination of [fullcalendar.io](https://fullcalendar.io/#demos) and a collection, where each contribution get's one markdown page (see https://github.com/RSE-leaders/SORSE20/issues/37#issuecomment-640239723)). As no one opposed this idea and it also matches what the people talked about today during the programme team call, I think we are good to go @vsoch :smiley:

shall I come up with some draft PR that contains an _events_ collection with some dummy events and you setup the calendar thing? We are not really in a hurry with this as we do not have submissions, yet

**Comment by vsoch** [comment]
Yes that would be great!

**Comment by Chilipp** [comment]
alright. I won't have time before Thursday, though

**Comment by Chilipp** [comment]
maybe wednesday

**Comment by vsoch** [comment]
@Chilipp you are unbelievably hard working on this site! Please take whatever time you need, I will be around when you are ready!

**Comment by Chilipp** [comment]
Thank you :blush:
